/*
 * This source file was generated by the Gradle 'init' task
 */
package my.java;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        assertEquals(Task1.getArray(1).length, 1);
    }
}
